services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgres://postgres:admin@host.docker.internal:5433/angeltrade
      - SERVER_API_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
