syntax = "proto3";

package product_category;
option go_package = "main-service/pb";

message ProductCategory {
    string id = 1;
    string name = 2;
    string slug = 3;
    string description = 4;
}

message CreateProductCategoryRequest {
    string name = 1;
    string description = 2;
}

message CreateProductCategoryResponse {
    ProductCategory data = 1;
    string message = 2;
}

message GetProductCategoriesRequest {
}

message GetProductCategoriesResponse {
    repeated ProductCategory data = 1;
    string message = 2;
}

service ProductCategoryService {
    rpc CreateProductCategory(CreateProductCategoryRequest) returns (CreateProductCategoryResponse);
    rpc GetProductCategories(GetProductCategoriesRequest) returns (GetProductCategoriesResponse);
}
