version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
      - "50051:50051"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:admin@host.docker.internal:5433/technostock
