FROM rust:latest

WORKDIR /app


RUN cargo install cargo-watch --version 8.4.1 --locked && \
    cargo install sqlx-cli --no-default-features --features postgres

COPY . .

EXPOSE 8000 50051

CMD ["cargo", "watch", "-c", "-x", "run"]
