// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: product_plan.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductPlanService_CreateProductPlan_FullMethodName           = "/product_plan.ProductPlanService/CreateProductPlan"
	ProductPlanService_GetProductPlansByCategoryId_FullMethodName = "/product_plan.ProductPlanService/GetProductPlansByCategoryId"
)

// ProductPlanServiceClient is the client API for ProductPlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductPlanServiceClient interface {
	CreateProductPlan(ctx context.Context, in *CreateProductPlanRequest, opts ...grpc.CallOption) (*CreateProductPlanResponse, error)
	GetProductPlansByCategoryId(ctx context.Context, in *GetProductPlansByCategoryIdRequest, opts ...grpc.CallOption) (*GetProductPlansResponse, error)
}

type productPlanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductPlanServiceClient(cc grpc.ClientConnInterface) ProductPlanServiceClient {
	return &productPlanServiceClient{cc}
}

func (c *productPlanServiceClient) CreateProductPlan(ctx context.Context, in *CreateProductPlanRequest, opts ...grpc.CallOption) (*CreateProductPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProductPlanResponse)
	err := c.cc.Invoke(ctx, ProductPlanService_CreateProductPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productPlanServiceClient) GetProductPlansByCategoryId(ctx context.Context, in *GetProductPlansByCategoryIdRequest, opts ...grpc.CallOption) (*GetProductPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductPlansResponse)
	err := c.cc.Invoke(ctx, ProductPlanService_GetProductPlansByCategoryId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductPlanServiceServer is the server API for ProductPlanService service.
// All implementations must embed UnimplementedProductPlanServiceServer
// for forward compatibility.
type ProductPlanServiceServer interface {
	CreateProductPlan(context.Context, *CreateProductPlanRequest) (*CreateProductPlanResponse, error)
	GetProductPlansByCategoryId(context.Context, *GetProductPlansByCategoryIdRequest) (*GetProductPlansResponse, error)
	mustEmbedUnimplementedProductPlanServiceServer()
}

// UnimplementedProductPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductPlanServiceServer struct{}

func (UnimplementedProductPlanServiceServer) CreateProductPlan(context.Context, *CreateProductPlanRequest) (*CreateProductPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductPlan not implemented")
}
func (UnimplementedProductPlanServiceServer) GetProductPlansByCategoryId(context.Context, *GetProductPlansByCategoryIdRequest) (*GetProductPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductPlansByCategoryId not implemented")
}
func (UnimplementedProductPlanServiceServer) mustEmbedUnimplementedProductPlanServiceServer() {}
func (UnimplementedProductPlanServiceServer) testEmbeddedByValue()                            {}

// UnsafeProductPlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductPlanServiceServer will
// result in compilation errors.
type UnsafeProductPlanServiceServer interface {
	mustEmbedUnimplementedProductPlanServiceServer()
}

func RegisterProductPlanServiceServer(s grpc.ServiceRegistrar, srv ProductPlanServiceServer) {
	// If the following call panics, it indicates UnimplementedProductPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductPlanService_ServiceDesc, srv)
}

func _ProductPlanService_CreateProductPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPlanServiceServer).CreateProductPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductPlanService_CreateProductPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPlanServiceServer).CreateProductPlan(ctx, req.(*CreateProductPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductPlanService_GetProductPlansByCategoryId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductPlansByCategoryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPlanServiceServer).GetProductPlansByCategoryId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductPlanService_GetProductPlansByCategoryId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPlanServiceServer).GetProductPlansByCategoryId(ctx, req.(*GetProductPlansByCategoryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductPlanService_ServiceDesc is the grpc.ServiceDesc for ProductPlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductPlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_plan.ProductPlanService",
	HandlerType: (*ProductPlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProductPlan",
			Handler:    _ProductPlanService_CreateProductPlan_Handler,
		},
		{
			MethodName: "GetProductPlansByCategoryId",
			Handler:    _ProductPlanService_GetProductPlansByCategoryId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product_plan.proto",
}
