// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: product_plan.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPlan) Reset() {
	*x = ProductPlan{}
	mi := &file_product_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPlan) ProtoMessage() {}

func (x *ProductPlan) ProtoReflect() protoreflect.Message {
	mi := &file_product_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPlan.ProtoReflect.Descriptor instead.
func (*ProductPlan) Descriptor() ([]byte, []int) {
	return file_product_plan_proto_rawDescGZIP(), []int{0}
}

func (x *ProductPlan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductPlan) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductPlan) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductPlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductPlan) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductPlanRequest) Reset() {
	*x = CreateProductPlanRequest{}
	mi := &file_product_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductPlanRequest) ProtoMessage() {}

func (x *CreateProductPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductPlanRequest.ProtoReflect.Descriptor instead.
func (*CreateProductPlanRequest) Descriptor() ([]byte, []int) {
	return file_product_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductPlanRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductPlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductPlanRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductPlanRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ProductPlan           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductPlanResponse) Reset() {
	*x = CreateProductPlanResponse{}
	mi := &file_product_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductPlanResponse) ProtoMessage() {}

func (x *CreateProductPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductPlanResponse.ProtoReflect.Descriptor instead.
func (*CreateProductPlanResponse) Descriptor() ([]byte, []int) {
	return file_product_plan_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductPlanResponse) GetData() *ProductPlan {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateProductPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProductPlansByCategoryIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductPlansByCategoryIdRequest) Reset() {
	*x = GetProductPlansByCategoryIdRequest{}
	mi := &file_product_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductPlansByCategoryIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductPlansByCategoryIdRequest) ProtoMessage() {}

func (x *GetProductPlansByCategoryIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductPlansByCategoryIdRequest.ProtoReflect.Descriptor instead.
func (*GetProductPlansByCategoryIdRequest) Descriptor() ([]byte, []int) {
	return file_product_plan_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductPlansByCategoryIdRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type GetProductPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductPlan         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductPlansResponse) Reset() {
	*x = GetProductPlansResponse{}
	mi := &file_product_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductPlansResponse) ProtoMessage() {}

func (x *GetProductPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductPlansResponse.ProtoReflect.Descriptor instead.
func (*GetProductPlansResponse) Descriptor() ([]byte, []int) {
	return file_product_plan_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductPlansResponse) GetData() []*ProductPlan {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProductPlansResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_product_plan_proto protoreflect.FileDescriptor

const file_product_plan_proto_rawDesc = "" +
	"\n" +
	"\x12product_plan.proto\x12\fproduct_plan\"\x9e\x01\n" +
	"\vProductPlan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"\x87\x01\n" +
	"\x18CreateProductPlanRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"d\n" +
	"\x19CreateProductPlanResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.product_plan.ProductPlanR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\"GetProductPlansByCategoryIdRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\"b\n" +
	"\x17GetProductPlansResponse\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.product_plan.ProductPlanR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf2\x01\n" +
	"\x12ProductPlanService\x12d\n" +
	"\x11CreateProductPlan\x12&.product_plan.CreateProductPlanRequest\x1a'.product_plan.CreateProductPlanResponse\x12v\n" +
	"\x1bGetProductPlansByCategoryId\x120.product_plan.GetProductPlansByCategoryIdRequest\x1a%.product_plan.GetProductPlansResponseB\x11Z\x0fmain-service/pbb\x06proto3"

var (
	file_product_plan_proto_rawDescOnce sync.Once
	file_product_plan_proto_rawDescData []byte
)

func file_product_plan_proto_rawDescGZIP() []byte {
	file_product_plan_proto_rawDescOnce.Do(func() {
		file_product_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_plan_proto_rawDesc), len(file_product_plan_proto_rawDesc)))
	})
	return file_product_plan_proto_rawDescData
}

var file_product_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_plan_proto_goTypes = []any{
	(*ProductPlan)(nil),                        // 0: product_plan.ProductPlan
	(*CreateProductPlanRequest)(nil),           // 1: product_plan.CreateProductPlanRequest
	(*CreateProductPlanResponse)(nil),          // 2: product_plan.CreateProductPlanResponse
	(*GetProductPlansByCategoryIdRequest)(nil), // 3: product_plan.GetProductPlansByCategoryIdRequest
	(*GetProductPlansResponse)(nil),            // 4: product_plan.GetProductPlansResponse
}
var file_product_plan_proto_depIdxs = []int32{
	0, // 0: product_plan.CreateProductPlanResponse.data:type_name -> product_plan.ProductPlan
	0, // 1: product_plan.GetProductPlansResponse.data:type_name -> product_plan.ProductPlan
	1, // 2: product_plan.ProductPlanService.CreateProductPlan:input_type -> product_plan.CreateProductPlanRequest
	3, // 3: product_plan.ProductPlanService.GetProductPlansByCategoryId:input_type -> product_plan.GetProductPlansByCategoryIdRequest
	2, // 4: product_plan.ProductPlanService.CreateProductPlan:output_type -> product_plan.CreateProductPlanResponse
	4, // 5: product_plan.ProductPlanService.GetProductPlansByCategoryId:output_type -> product_plan.GetProductPlansResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_plan_proto_init() }
func file_product_plan_proto_init() {
	if File_product_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_plan_proto_rawDesc), len(file_product_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_plan_proto_goTypes,
		DependencyIndexes: file_product_plan_proto_depIdxs,
		MessageInfos:      file_product_plan_proto_msgTypes,
	}.Build()
	File_product_plan_proto = out.File
	file_product_plan_proto_goTypes = nil
	file_product_plan_proto_depIdxs = nil
}
