// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: product_category.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCategory) Reset() {
	*x = ProductCategory{}
	mi := &file_product_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCategory) ProtoMessage() {}

func (x *ProductCategory) ProtoReflect() protoreflect.Message {
	mi := &file_product_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCategory.ProtoReflect.Descriptor instead.
func (*ProductCategory) Descriptor() ([]byte, []int) {
	return file_product_category_proto_rawDescGZIP(), []int{0}
}

func (x *ProductCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCategory) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProductCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductCategoryRequest) Reset() {
	*x = CreateProductCategoryRequest{}
	mi := &file_product_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductCategoryRequest) ProtoMessage() {}

func (x *CreateProductCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateProductCategoryRequest) Descriptor() ([]byte, []int) {
	return file_product_category_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProductCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ProductCategory       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductCategoryResponse) Reset() {
	*x = CreateProductCategoryResponse{}
	mi := &file_product_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductCategoryResponse) ProtoMessage() {}

func (x *CreateProductCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateProductCategoryResponse) Descriptor() ([]byte, []int) {
	return file_product_category_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductCategoryResponse) GetData() *ProductCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateProductCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProductCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCategoriesRequest) Reset() {
	*x = GetProductCategoriesRequest{}
	mi := &file_product_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCategoriesRequest) ProtoMessage() {}

func (x *GetProductCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetProductCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_product_category_proto_rawDescGZIP(), []int{3}
}

type GetProductCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductCategory     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductCategoriesResponse) Reset() {
	*x = GetProductCategoriesResponse{}
	mi := &file_product_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductCategoriesResponse) ProtoMessage() {}

func (x *GetProductCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetProductCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_product_category_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductCategoriesResponse) GetData() []*ProductCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetProductCategoriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_product_category_proto protoreflect.FileDescriptor

const file_product_category_proto_rawDesc = "" +
	"\n" +
	"\x16product_category.proto\x12\x10product_category\"k\n" +
	"\x0fProductCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"T\n" +
	"\x1cCreateProductCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"p\n" +
	"\x1dCreateProductCategoryResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.product_category.ProductCategoryR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1d\n" +
	"\x1bGetProductCategoriesRequest\"o\n" +
	"\x1cGetProductCategoriesResponse\x125\n" +
	"\x04data\x18\x01 \x03(\v2!.product_category.ProductCategoryR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x89\x02\n" +
	"\x16ProductCategoryService\x12x\n" +
	"\x15CreateProductCategory\x12..product_category.CreateProductCategoryRequest\x1a/.product_category.CreateProductCategoryResponse\x12u\n" +
	"\x14GetProductCategories\x12-.product_category.GetProductCategoriesRequest\x1a..product_category.GetProductCategoriesResponseB\x11Z\x0fmain-service/pbb\x06proto3"

var (
	file_product_category_proto_rawDescOnce sync.Once
	file_product_category_proto_rawDescData []byte
)

func file_product_category_proto_rawDescGZIP() []byte {
	file_product_category_proto_rawDescOnce.Do(func() {
		file_product_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_category_proto_rawDesc), len(file_product_category_proto_rawDesc)))
	})
	return file_product_category_proto_rawDescData
}

var file_product_category_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_category_proto_goTypes = []any{
	(*ProductCategory)(nil),               // 0: product_category.ProductCategory
	(*CreateProductCategoryRequest)(nil),  // 1: product_category.CreateProductCategoryRequest
	(*CreateProductCategoryResponse)(nil), // 2: product_category.CreateProductCategoryResponse
	(*GetProductCategoriesRequest)(nil),   // 3: product_category.GetProductCategoriesRequest
	(*GetProductCategoriesResponse)(nil),  // 4: product_category.GetProductCategoriesResponse
}
var file_product_category_proto_depIdxs = []int32{
	0, // 0: product_category.CreateProductCategoryResponse.data:type_name -> product_category.ProductCategory
	0, // 1: product_category.GetProductCategoriesResponse.data:type_name -> product_category.ProductCategory
	1, // 2: product_category.ProductCategoryService.CreateProductCategory:input_type -> product_category.CreateProductCategoryRequest
	3, // 3: product_category.ProductCategoryService.GetProductCategories:input_type -> product_category.GetProductCategoriesRequest
	2, // 4: product_category.ProductCategoryService.CreateProductCategory:output_type -> product_category.CreateProductCategoryResponse
	4, // 5: product_category.ProductCategoryService.GetProductCategories:output_type -> product_category.GetProductCategoriesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_category_proto_init() }
func file_product_category_proto_init() {
	if File_product_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_category_proto_rawDesc), len(file_product_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_category_proto_goTypes,
		DependencyIndexes: file_product_category_proto_depIdxs,
		MessageInfos:      file_product_category_proto_msgTypes,
	}.Build()
	File_product_category_proto = out.File
	file_product_category_proto_goTypes = nil
	file_product_category_proto_depIdxs = nil
}
